[build]
command = 'npm run productionBuild && npm run optimizeFonts'
publish = 'dist'

[[redirects]]
from = '/*'
status = 200
to = 'index.html'

[[headers]]
for = '/'
[headers.values]
Link = '</index.js>; rel=preload; as=script'
